# Generated by Django 4.0.2 on 2022-02-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='card_set_code',
            field=models.CharField(default='set code', max_length=20, verbose_name='Set Code'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='card_set_rarity',
            field=models.CharField(default='rarity', max_length=30, verbose_name='Rarity'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='card_attribute',
            field=models.CharField(default='attribute', max_length=20, verbose_name='Attribute'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='card_description',
            field=models.TextField(default='desc', verbose_name='Effect/Description'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='card_name',
            field=models.CharField(default='name', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='card_type',
            field=models.CharField(default='type', max_length=100, verbose_name='Type'),
        ),
    ]
