# Generated by Django 4.0.2 on 2022-02-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cardmodel_card_set_code_cardmodel_card_set_rarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='card_race',
            field=models.CharField(default='race', max_length=20, verbose_name='Race'),
        ),
    ]
