# Generated by Django 4.0.2 on 2022-04-17 19:42

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_wallet_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardonsale',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Creation date'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_status',
            field=models.CharField(choices=[('Payment approved', 'Payment approved'), ('In transit', 'In transit'), ('Finished', 'Finished')], default=django.utils.timezone.now, max_length=50, verbose_name='Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Latest update'),
        ),
    ]
