# Generated by Django 4.0.2 on 2022-02-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cardmodel_card_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardmodel',
            name='card_set_code',
        ),
        migrations.RemoveField(
            model_name='cardmodel',
            name='card_set_rarity',
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='card_level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Level/Rank/Link'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='card_race',
            field=models.CharField(default='race', max_length=20, verbose_name='Class'),
        ),
    ]
