# Generated by Django 4.0.2 on 2022-02-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cardmodel_card_set_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='card_attribute',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Attribute'),
        ),
    ]
