# Generated by Django 4.0.2 on 2022-05-04 18:28

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_orders_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='buyer_address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.AddField(
            model_name='orders',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Bought by'),
        ),
        migrations.AddField(
            model_name='orders',
            name='customer_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.useraddress'),
        ),
        migrations.AddField(
            model_name='orders',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cardonsale',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cardonsale',
            name='rarity',
            field=models.CharField(default='rare', max_length=40),
        ),
        migrations.AlterField(
            model_name='cardonsale',
            name='seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.orders')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cardonsale')),
            ],
        ),
    ]
