# Generated by Django 4.0.2 on 2022-02-25 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cardmodel_card_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardmodel',
            name='card_ability',
        ),
    ]
