# Generated by Django 4.0.2 on 2022-03-08 19:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_remove_cardmodel_card_ability'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOnSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price')),
                ('card_set', models.CharField(default='XXXX-000', max_length=20, verbose_name='Set')),
                ('card_rarity', models.CharField(default='rare', max_length=40, verbose_name='Rarity')),
                ('card_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('card_region', models.CharField(choices=[('PT_BR', 'Brazilian Portuguese'), ('EN_US', 'English'), ('FR', 'French'), ('IT', 'Italian'), ('DE', 'German'), ('ES', 'Spanish'), ('JP', 'Japanese'), ('KR', 'Korean'), ('CN', 'Chinese'), ('EN_OCG', 'English (Asian)')], max_length=20)),
                ('card_condition', models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], max_length=20)),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cardmodel', verbose_name='Card ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
        ),
    ]
