# Generated by Django 4.0.2 on 2022-03-09 14:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_cardonsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('state_province', models.CharField(max_length=100, verbose_name='State/Province')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
            ],
        ),
        migrations.RemoveField(
            model_name='cardonsale',
            name='user_id',
        ),
        migrations.AddField(
            model_name='cardonsale',
            name='seller_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Seller ID'),
        ),
        migrations.AlterField(
            model_name='cardonsale',
            name='card_amount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='cardonsale',
            name='card_condition',
            field=models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], max_length=20, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='cardonsale',
            name='card_region',
            field=models.CharField(choices=[('PT_BR', 'Brazilian Portuguese'), ('EN_US', 'English'), ('FR', 'French'), ('IT', 'Italian'), ('DE', 'German'), ('ES', 'Spanish'), ('JP', 'Japanese'), ('KR', 'Korean'), ('CN', 'Chinese'), ('EN_OCG', 'English (Asian)')], max_length=20, verbose_name='Region'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('user_sales', models.IntegerField(default=0, verbose_name='Sales Amount')),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraddress')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
    ]
