# Generated by Django 4.0.2 on 2022-05-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_orders_shipping_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='total_price',
        ),
    ]
