# Generated by Django 4.0.2 on 2022-03-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_user_address_userprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardmodel',
            old_name='card_atk',
            new_name='attack',
        ),
        migrations.RenameField(
            model_name='cardmodel',
            old_name='card_attribute',
            new_name='attribute',
        ),
        migrations.RenameField(
            model_name='cardmodel',
            old_name='card_def',
            new_name='defense',
        ),
        migrations.RenameField(
            model_name='cardmodel',
            old_name='card_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cardmodel',
            old_name='card_level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='cardmodel',
            old_name='card_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cardmodel',
            old_name='card_race',
            new_name='race',
        ),
        migrations.RenameField(
            model_name='cardmodel',
            old_name='card_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='cardonsale',
            old_name='card_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='cardonsale',
            old_name='card_id',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='cardonsale',
            old_name='card_condition',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='cardonsale',
            old_name='card_rarity',
            new_name='rarity',
        ),
        migrations.RenameField(
            model_name='cardonsale',
            old_name='card_region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='cardonsale',
            old_name='seller_id',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='cardonsale',
            old_name='card_set',
            new_name='set',
        ),
    ]
