# Generated by Django 4.0.2 on 2022-03-14 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_card_atk_cardmodel_attack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.useraddress'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sales',
            field=models.IntegerField(default=0, verbose_name='Sales Amount'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
