# Generated by Django 4.0.2 on 2022-03-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_address_user_bio_user_sales_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
