# Generated by Django 4.0.2 on 2022-03-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_user_address_useraddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardonsale',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='List'),
        ),
    ]
