# Generated by Django 4.0.2 on 2022-04-04 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_cardonsale_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='name',
            field=models.CharField(default='name', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cardonsale',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cardmodel', verbose_name='Card name'),
        ),
        migrations.AlterField(
            model_name='cardonsale',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Visible?'),
        ),
    ]
